const names=['Renji Abarai',
    'Sōsuke Aizen',
    'Alucard',
    'Android 17',
    'Alex Louis Armstrong',
    'Hao Asakura',
    'Yoh Asakura',
    'Astro Boy',
    'Shinn Asuka',
    'Char Aznable',
    'Sergio Batista',
    'Batou',
    'Beerus',    
    'Beyond the Grave',
    'Black Jack',
    'Black Star',
    'Legato Bluesummers',
    'King Bradley',
    'Dio Brando',
    'Brock',
    'Broly',
    'Cell',
    'Cross Marian',
    'Osamu Dazai',
    'Natsu Dragneel',
    'Ryoma Echizen',
    'Alphonse Elric',
    'Edward Elric',
    'Kiritsugu Emiya',
    'Shirou Emiya',
    'Luke fon Fabre',
    'Frieza',
    'Akira Fudo',
    'Gaara',
    'Gourry Gabriev',
    'Gohan',
    'Goku',
    'Hayato Gokudera',
    'Griffith',
    'Tadashi Hamada',
    'Captain Harlock',
    'Haseo',
    'Kakashi Hatake',
    'Kyoya Hibari',
    'Himura Kenshin',
    'Saito Hiraga',
    'Yoichi Hiruma',
    'Tōshirō Hitsugaya',
    'Van Hohenheim',
    'Bertolt Hoover',
    'Maes Hughes',
    'Cygnus Hyoga',
    'Hikaru Ichijyo',
    'Gin Ichimaru',
    'Gendo Ikari',
    'Shinji Ikari',
    'Phoenix Ikki',
    'Inuyasha',
    'Matt Ishida']
export default names